# Generated by Django 5.2.17 on 2026-08-05 13:26

import apps.accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unsubmitted', 'Not submitted'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('national_id_number', models.CharField(max_length=20, verbose_name='national ID number')),
                ('national_id_front', models.ImageField(upload_to='verification/id/', validators=[apps.accounts.validators.MaxFileSizeValidator(8388608)], verbose_name='national ID (front)')),
                ('national_id_back', models.ImageField(blank=True, null=True, upload_to='verification/id/', validators=[apps.accounts.validators.MaxFileSizeValidator(8388608)], verbose_name='national ID (back)')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='verification/selfie/', validators=[apps.accounts.validators.MaxFileSizeValidator(8388608)], verbose_name='selfie holding your ID')),
                ('reviewer_notes', models.TextField(blank=True, max_length=800)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ownership_proof_type', models.CharField(choices=[('title_deed', 'Title deed'), ('sale_agreement', 'Sale agreement'), ('management_letter', 'Property management letter'), ('agency_licence', 'Agency licence'), ('video_call', 'Video call verification')], max_length=24, verbose_name='proof of control')),
                ('ownership_document', models.FileField(blank=True, help_text='Not required if you chose video call verification.', null=True, upload_to='verification/ownership/', validators=[apps.accounts.validators.MaxFileSizeValidator(8388608)], verbose_name='supporting document')),
                ('property_address', models.CharField(help_text='The building or estate the document refers to.', max_length=200)),
                ('video_call_slot', models.DateTimeField(blank=True, help_text='Preferred time for the verification call, if applicable.', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'landlord verification',
                'verbose_name_plural': 'landlord verifications',
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unsubmitted', 'Not submitted'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('national_id_number', models.CharField(max_length=20, verbose_name='national ID number')),
                ('national_id_front', models.ImageField(upload_to='verification/id/', validators=[apps.accounts.validators.MaxFileSizeValidator(8388608)], verbose_name='national ID (front)')),
                ('national_id_back', models.ImageField(blank=True, null=True, upload_to='verification/id/', validators=[apps.accounts.validators.MaxFileSizeValidator(8388608)], verbose_name='national ID (back)')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='verification/selfie/', validators=[apps.accounts.validators.MaxFileSizeValidator(8388608)], verbose_name='selfie holding your ID')),
                ('reviewer_notes', models.TextField(blank=True, max_length=800)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_name', models.CharField(blank=True, max_length=140)),
                ('income_document', models.FileField(blank=True, help_text='Optional. Some landlords ask for proof of income.', null=True, upload_to='verification/income/', validators=[apps.accounts.validators.MaxFileSizeValidator(8388608)], verbose_name='payslip or M-Pesa statement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tenant verification',
                'verbose_name_plural': 'tenant verifications',
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
    ]
