# Generated by Django 5.2.17 on 2026-08-05 13:26

import apps.accounts.validators
import apps.listings.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('property_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('single', 'Single room'), ('apartment', 'Apartment'), ('maisonette', 'Maisonette'), ('bungalow', 'Bungalow'), ('shared', 'Shared house')], default='apartment', max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1, help_text='Use 0 for a bedsitter.', validators=[django.core.validators.MaxValueValidator(10)])),
                ('bathrooms', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)])),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1000'))], verbose_name='monthly rent (KES)')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='deposit (KES)')),
                ('county', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kiambu', 'Kiambu'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Mombasa', 'Mombasa'), ('Kilifi', 'Kilifi'), ('Nakuru', 'Nakuru'), ('Uasin Gishu', 'Uasin Gishu'), ('Kisumu', 'Kisumu'), ('Nyeri', 'Nyeri'), ('Meru', 'Meru'), ('Kakamega', 'Kakamega')], max_length=60)),
                ('area', models.CharField(help_text='e.g. Ruaka, Membley, Nyali', max_length=120, verbose_name='estate / area')),
                ('landmark_description', models.TextField(help_text='Directions the way people actually navigate, e.g. "200m from Quickmart Ruaka, blue gate, third building past the mosque".', max_length=600, verbose_name='how to find it')),
                ('nearest_landmark', models.CharField(help_text='e.g. Quickmart Ruaka, Ruaka Stage, Membley Police Post', max_length=140, verbose_name='nearest well-known landmark')),
                ('walking_minutes_to_landmark', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='walking minutes from that landmark')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Optional. Landmarks come first; a pin is a bonus.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-5')), django.core.validators.MaxValueValidator(Decimal('5.5'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('33.5')), django.core.validators.MaxValueValidator(Decimal('42'))])),
                ('walkthrough_video_url', models.URLField(blank=True, help_text='Optional YouTube/Drive link to a full walk-through of the unit.', verbose_name='walkthrough video link')),
                ('water_supply', models.CharField(choices=[('borehole', 'Borehole'), ('council', 'County water'), ('tank', 'Tank / delivered'), ('both', 'Borehole + county')], default='council', max_length=20)),
                ('has_water_included', models.BooleanField(default=False, verbose_name='water included in rent')),
                ('has_parking', models.BooleanField(default=False, verbose_name='parking')),
                ('has_security', models.BooleanField(default=False, verbose_name='gated / security')),
                ('has_borehole_backup', models.BooleanField(default=False, verbose_name='water backup')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='furnished')),
                ('allows_pets', models.BooleanField(default=False, verbose_name='pets allowed')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published'), ('rented', 'Rented out'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('available_from', models.DateField(default=django.utils.timezone.localdate)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.listings.models.listing_photo_path, validators=[apps.accounts.validators.MaxFileSizeValidator(8388608)])),
                ('category', models.CharField(choices=[('exterior', 'Building exterior'), ('entrance', 'Gate / entrance'), ('room', 'Room interior'), ('meter', 'Water / electricity meter'), ('landmark', 'Nearest landmark'), ('other', 'Other')], default='room', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-published_at'], name='listings_li_status_477a45_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['county', 'area'], name='listings_li_county_e6850c_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['rent_amount'], name='listings_li_rent_am_2f71b2_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['bedrooms'], name='listings_li_bedroom_f890fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedlisting',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='unique_saved_listing'),
        ),
    ]
